language: node_js
node_js:
- 4
deploy:
  provider: npm
  email: accounts@acloud.guru
  api_key:
    secure: Gyt/F8ljOSeGVPuihbGFBGNuMxB9c/QQBlKWmHNpGl59I/cHMNSn4bXw2HehLNlh5Wzj3wky2QEJxAyswAW8btH+BJSCQ2P4I8oBqk1Fw0DahfETQK2ut70VP3SUs2KlmQXxpYgxo6amMDKSgTUhqJiQ0zqZxcQTa1f/bc2ArliUu0SElfbjXE13pX6wu8zPR/LTJhYjtRTn4Duy/jLRAFHSEuPHcEHSQ2W/nkHCtZ6LlSTy19Jfwpn4gpgRSw5ldNTO+1MQrTA+W6zGGL9h7T4FmEV5l7mUhncHjmAf6plSnIzYMY9IqjWv0rRPZpZwB/miJdEWOcsb5xr+js/sBOgda3nU5b5nFwxzQsP+/FGQMF3Y16ttxbAwg9KHWc/1aBkHisdKTfkaDeq3jZDJSrvF7eXdx/Zy3vTmykL/5+SUw7ZyqzgrVh1xNiU8T2F7PDOdvOdNIwaaM91eoa5FQdFh29eE6lSCF89niBCbXTwnVzn6/m3EIQ9hOgholGZmPmpyWUHyNmmC1jZqbE6B9pO4pxMFdFPZmnqCCzPJKPTGgb13ax8060A8Y0gy5FRCv2gDGcvR1ZLq0kbnf/kXfqW9O6zxnMjhawq3BBTBJiR25235jLL6d/k1WeoUTLghtoV0+tvUsRJSNmJYPcVltAj56wil0IPIzZnyisnEWw0=
  on:
    tags: true
    repo: ACloudGuru/serverless-plugin-cloudwatch-sumologic
    branch: master
notifications:
  slack:
    secure: SaUa30/K66GlD/kNcluWwnLjg3yWgYYNehi9kIZLzXsvnTEVuv6YJasbTGuOojrBQKQqAJLutmPedvec0AG4bbC4ltlIunvKpUCW+klOs3v0Dmi7mpwvWSJJwxIYCdwzJdqB7IiQtQfZtBbJTx+cL2fSsy1LvBEiOZiYLd+xjpiP6YpWgQocVln3nrsPqUFfFetZWy5hR6O6yPNPYjIjt0xe6OV5Ku9SIJx6EZXrJBZMDK0BXT06qYnYHJEpw3WBGOJ2M78+EBs2Ibd3NuvCzzq1pUUTdICrEy5bYjHR0i7Dtw3Vaf/LdA2QHTRnjmu8HJrA3SOUyIwubrYSMhQq3j0MQW446XUkyPDNTDAfkP2vdJOdOS8l3btZPtLB+Kgw9g6IUFc3QV+h2inXooRc7+1S4Gxi/0fiStCFwP4mY954E+GgIK+hBewh/On76YHawSX6X5HDl9L+gJEnU9kHvdo1sFzMIDvJz/eTMYo9TN3RHtRokc2pWz46C5QwB9iGkP4OptA1ri6pzdKTe3w94cZ5+fIoLnt7LACzrKp3PUCzWa6bnA5zgl5TKv994lfs02Cg3hJJn6mfTTDVN18FpD+8xQEzfOrsipyuvTWCvWfsce8t6SSs8a09mk1Kb/rDpcp5v6vcC7xGBwwaOzKpAQZNvXA7J45VonDOWocyvDU=
